# Generated by Django 5.1.2 on 2024-10-31 06:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemontool', '0002_rename_card_image_pokemoncard_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemoncard',
            name='attack1_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='attack1_damage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='attack1_info',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='attack1_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='attack1_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='attack2_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='attack2_damage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='attack2_info',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='attack2_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='attack2_type',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='collection_number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='evolution_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='evolution_photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='evolutions/'),
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='evolution_stage',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='illustrator',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='length',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='rarity',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='resistance_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='resistance_element',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='retreat_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='specialty',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='weakness_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='weakness_element',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='weight',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pokemoncard',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pokemoncard',
            name='hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemoncard',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='pokemoncard',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
